name: Test Environment Variables

on:
  push:
    branches:
      - main  # Executa o workflow ao fazer push na branch principal
  workflow_dispatch:  # Permite executar manualmente

jobs:
  test-secrets:
    runs-on: ubuntu-latest

    steps:
    # 1. Fazer checkout do código no repositório
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Testar se os secrets estão definidos
    - name: Test environment variables
      run: |
        echo "Testing environment variables..."
        
        # Função para testar se a variável está definida
        test_var() {
          if [ -z "${!1}" ]; then
            echo "$1 is not defined!"
          else
            echo "$1 is set to: ${!1}"
          fi
        }

        # Testar os secrets
        test_var "SUBSCRIPTION_KEY"
        test_var "ENDPOINT"
        test_var "LOCATION"
        test_var "API_KEY"
        test_var "API_VERSION"
      env:  # Passando os secrets como variáveis de ambiente para o script
        SUBSCRIPTION_KEY: ${{ secrets.SUBSCRIPTION_KEY }}
        ENDPOINT: ${{ secrets.ENDPOINT }}
        LOCATION: ${{ secrets.LOCATION }}
        API_KEY: ${{ secrets.API_KEY }}
        API_VERSION: ${{ secrets.API_VERSION }}
