name: Test Environment Variables

on:
  push:
    branches:
      - main  # Executa o workflow ao fazer push na branch principal
  workflow_dispatch:  # Permite executar manualmente

jobs:
  test-secrets:
    runs-on: ubuntu-latest

    steps:
    # 1. Fazer checkout do c칩digo no reposit칩rio
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurar o ambiente Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. Verificar as vari치veis de ambiente
    - name: Test Environment Variables
      env:  # Passar os secrets como vari치veis de ambiente
        SUBSCRIPTION_KEY: ${{ secrets.SUBSCRIPTION_KEY }}
        ENDPOINT: ${{ secrets.ENDPOINT }}
        LOCATION: ${{ secrets.LOCATION }}
        AZURE_ENDPOINT: ${{ secrets.AZURE_ENDPOINT }}
        API_KEY: ${{ secrets.API_KEY }}
        API_VERSION: ${{ secrets.API_VERSION }}
      run: |
        echo "Testing environment variables..."
        echo "SUBSCRIPTION_KEY is set to: $SUBSCRIPTION_KEY"
        echo "ENDPOINT is set to: $ENDPOINT"
        echo "LOCATION is set to: $LOCATION"
        echo "AZURE_ENDPOINT is set to: $AZURE_ENDPOINT"
        echo "API_KEY is set to: $API_KEY"
        echo "API_VERSION is set to: $API_VERSION"
