name: Test Environment Variables

on:
  push:
    branches:
      - main  # Executa o workflow ao fazer push na branch principal
  workflow_dispatch:  # Permite executar manualmente

jobs:
  test-secrets:
    runs-on: ubuntu-latest

    steps:
    # 1. Fazer checkout do código no repositório
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurar o ambiente Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. Testar a presença das variáveis de ambiente sem imprimir os valores
    - name: Test Environment Variables
      env:  # Passar os secrets como variáveis de ambiente
        SUBSCRIPTION_KEY: ${{ secrets.SUBSCRIPTION_KEY }}
        ENDPOINT: ${{ secrets.ENDPOINT }}
        LOCATION: ${{ secrets.LOCATION }}
        AZURE_ENDPOINT: ${{ secrets.AZURE_ENDPOINT }}
        API_KEY: ${{ secrets.API_KEY }}
        API_VERSION: ${{ secrets.API_VERSION }}
      run: |
        echo "Testing environment variables..."
        if [ -z "$SUBSCRIPTION_KEY" ]; then echo "SUBSCRIPTION_KEY is missing!"; else echo "SUBSCRIPTION_KEY is set."; fi
        if [ -z "$ENDPOINT" ]; then echo "ENDPOINT is missing!"; else echo "ENDPOINT is set."; fi
        if [ -z "$LOCATION" ]; then echo "LOCATION is missing!"; else echo "LOCATION is set."; fi
        if [ -z "$AZURE_ENDPOINT" ]; then echo "AZURE_ENDPOINT is missing!"; else echo "AZURE_ENDPOINT is set."; fi
        if [ -z "$API_KEY" ]; then echo "API_KEY is missing!"; else echo "API_KEY is set."; fi
        if [ -z "$API_VERSION" ]; then echo "API_VERSION is missing!"; else echo "API_VERSION is set."; fi
