name: Test GitHub Secrets

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Test Environment Variables
      env:  # Passar os secrets como variáveis de ambiente
        SUBSCRIPTION_KEY: ${{ secrets.SUBSCRIPTION_KEY }}
        ENDPOINT: ${{ secrets.ENDPOINT }}
        LOCATION: ${{ secrets.LOCATION }}
      run: |
        echo "Testing environment variables..."
        echo "SUBSCRIPTION_KEY is set to: $SUBSCRIPTION_KEY"
        echo "ENDPOINT is set to: $ENDPOINT"
        echo "LOCATION is set to: $LOCATION"
